ARG DOCKER_REGISTRY
FROM ${DOCKER_REGISTRY}nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY /dist/ /usr/share/nginx/html/launcher/
COPY entrypoint.sh /usr/bin
RUN chmod a+x /usr/bin/entrypoint.sh
CMD ["entrypoint.sh"]

